# Generated by Django 6.0.5 on 2026-06-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='product',
            name='product_price_positive',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0), ('price__lt', 99999999)), name='product_price_positive', violation_error_message='Ціна повинна бути від 0 до 9999999'),
        ),
        migrations.AlterConstraint(
            model_name='product',
            name='product_stock_positive',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_stock_positive', violation_error_message='Кількість товару повинна бути більше або дорівнювати 0'),
        ),
    ]
