# Generated by Django 6.0.5 on 2026-06-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_comment_author_alter_comment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума')),
                ('customer_name', models.CharField(max_length=255, verbose_name="Ім'я покупця")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-id'],
            },
        ),
    ]
